### PR TITLE
[IIIF-964] Allow service array on any resource

### PR DESCRIPTION
**Pull request by markmatney**
Changes:
- add `setServices()` (plural) to all resource types
- remove `setService()` (singular)
- fix GenericService serialization (unpredictable property ordering and null pointer error)
- update tests and test fixtures

Reference: https://iiif.io/api/presentation/3.0/#service.

### CODE REVIEW

**Comment by markmatney** [comment]
I just realized that the method naming is going to be a problem when we do IIIF-966. Should I change back to `setService()`?

**Comment by ksclarke** [comment]
If they're plural I think it should be `setServices()` With the setter annotation you can set the property name to whatever you want, it doesn't have to be the same as the method name. Or am I misunderstanding... why will it be a problem?

**Comment by ksclarke** [comment]
Bleh... an array set with a singular property. How do you feel about `setServiceDefinitions()` / `getServiceDefinitions()` since these are supposed to be the things that the services in `service` refer to? Or `setServiceDefs()` / `getServiceDefs()` if the other is too long... or something else? I'd prefer a plural though since it's referring to an array.

**Comment by ksclarke** [comment]
How about we leave these as `getServices()` / `setServices()` and change the `services` property accessors to `setServiceDefs()` / `getServiceDefs()` since they're supposed to be the definitions at the top level that these services refer to?

**Comment by markmatney** [comment]
That sounds good. I left a note in the ticket for whoever ends up implementing `services`.

**Review by DRickard — DISMISSED** [review]

**Review by ksclarke — CHANGES_REQUESTED** [review]
Looks good, but I think it would be good to use `Service<? extends Service<?>>` instead of just the open wildcard `Service<?>`.

**Comment by ksclarke** [comment]
We chatted some more and decided to remove the generics from the Service interface altogether.

**Review by ksclarke — APPROVED** [review]

**Review by DRickard — APPROVED** [review]

**Pull request merged**
